export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const INCREASE_QUANTITY = "INCREASE_QUANTITY";

export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
